---
:tddium:
  :hooks:
    :pre: echo "Pre Hook"
    :worker: bundle exec rake db:setup
    :post: echo "Post Hook"
    :post_worker: printenv TDDIUM_MODE
    :post_build: printenv TDDIUM_BUILD_STATUS
